### ISSUE TITLE
Проверка дз: Про кофемат, про расход бензина (сколько км можно проехать)

### ISSUE THREAD

**Issue by Targonkp** [Targonkp/homework#2]
По автотестам всё работает нормально - ответы правильные.  Но в console.log в index.html (скрипты по обеим задачкам подключил к одной странице html) почему-то говорит о синтаксической ошибке:
Uncaught SyntaxError: Unexpected token export coffeemaker.js:1
 Uncaught SyntaxError: Unexpected token export gasoline.js:1 .

**Comment by coursar** [comment]
```javascript
<script src="app/coffeemaker.js"></script>
<script src="app/gasoline.js"></script>
```

Должно быть:
```javascript
<script src="app/coffeemaker.js" type="module"></script>
<script src="app/gasoline.js" type="module"></script>
```

**Comment by coursar** [comment]
Исправить #3, #4, #5, #6, #7
